version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: eventsproject-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventsProject
      MYSQL_USER: events_user 
      MYSQL_PASSWORD: Mahdi71445508@  
    ports:
      - "3307:3306"
    networks:
      - events-network
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  spring-app:
    image: mahdibelhajsaid/eventsproject:latest
    container_name: eventsproject-app
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/eventsProject?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: events_user
      SPRING_DATASOURCE_PASSWORD: Mahdi71445508@ 
    ports:
      - "8089:8089"
    networks:
      - events-network
    restart: on-failure

networks:
  events-network:
    driver: bridge

volumes:
  mysql-data: