version: '3.8'

services:
  # Service MySQL
  mysql-db:
    image: mysql:8.0
    container_name: eventsproject-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventsProject
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - events-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 20s
      retries: 10
      interval: 10s

  # Service Spring Boot
  spring-app:
    image: mahdibelhajsaid/eventsproject:latest
    container_name: eventsproject-app
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      # Configuration de la base de donn√©es pour pointer vers le conteneur MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/eventsProject?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8089:8089"  # Port externe:Port interne (tous les deux 8089)
    networks:
      - events-network
    restart: on-failure

networks:
  events-network:
    driver: bridge

volumes:
  mysql-data: